# Generated by Django 4.2.7 on 2023-11-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
